# See the documentation for more information:
# https://packit.dev/docs/configuration/
specfile_path: packaging/umockdev.spec

upstream_package_name: umockdev
downstream_package_name: umockdev

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-development-x86_64
        - fedora-development-i386
        - fedora-development-aarch64
        - fedora-development-ppc64le
        - fedora-development-s390x
        - fedora-development-armhfp
