#!/bin/sh
set -eu

# keep container around if $DEBUG is set, and allow strace
RM=""
[ -n "${DEBUG:-}" ] && OPTS="--privileged" || OPTS="--rm"

sudo docker run --interactive $OPTS --volume `pwd`:/source alpine:${RELEASE:-latest} /bin/sh <<EOF

# install build dependencies
apk add --no-cache autoconf automake libtool gcc musl-dev glib-dev eudev-dev libgudev-dev make vala linux-headers xz

# run build as user
su -s /bin/sh - guest << EOG
set -ex
cp -r /source /tmp
cd /tmp/source
./autogen.sh
make -j4
make check
EOG

EOF
