#!/bin/sh
set -eu

# keep container around if $DEBUG is set
[ -n "${DEBUG:-}" ] || OPTS="--rm"

if type podman >/dev/null 2>&1; then
    RUNC=podman
else
    RUNC="sudo docker"
fi

$RUNC run --interactive ${OPTS:-} --volume `pwd`:/source alpine:${RELEASE:-latest} /bin/sh <<EOF

# install build dependencies
apk add --no-cache autoconf automake libtool gcc musl-dev glib-dev eudev-dev libgudev-dev make vala linux-headers xz usbutils

# run build as user
su -s /bin/sh - guest << EOG
set -ex
export MAKEFLAGS="-j$(nproc)"
cp -r /source /tmp
cd /tmp/source
./autogen.sh
make -j4
make check
EOG

EOF
