#!/bin/sh
set -eu

# keep container around if $DEBUG is set
[ -n "${DEBUG:-}" ] || OPTS="--rm"

if type podman >/dev/null 2>&1; then
    RUNC=podman
else
    RUNC="sudo docker"
fi

$RUNC run --interactive ${OPTS:-} --volume `pwd`:/source docker.io/fedora:${RELEASE:-latest} /bin/sh << EOF
set -eu
dnf -y update

# install build dependencies
dnf -y install autoconf automake gcc glib2-devel gtk-doc libgudev1-devel libtool libudev-devel make python3-gobject-base usbutils vala xz systemd-udev valgrind

# run build as user
useradd guest
su -s /bin/sh - guest << EOG
set -eux
export MAKEFLAGS="-j$(nproc)"
cp -r /source /tmp
cd /tmp/source
./autogen.sh
make
make check
make check-valgrind
EOG

EOF
