#!/bin/sh
set -eu

# keep container around if $DEBUG is set
[ -n "${DEBUG:-}" ] || OPTS="--rm"

if type podman >/dev/null 2>&1; then
    RUNC=podman
else
    RUNC="sudo docker"
fi

$RUNC run --interactive ${OPTS:-} --volume `pwd`:/source docker.io/centos:${RELEASE:-latest} /bin/sh << EOF

# install build dependencies
dnf -y --enablerepo=PowerTools install autoconf automake gcc glib2-devel gtk-doc libgudev1-devel libtool libudev-devel make python3 python3-gobject-base usbutils vala

# run build as user
useradd guest
su -s /bin/sh - guest << EOG
set -ex
cp -r /source /tmp
cd /tmp/source
./autogen.sh
make -j4
make check
EOG

EOF
